### ISSUE TITLE
Doesn't work in Symfony 6.2

### ISSUE THREAD

**Issue by Valmonzo** [Gregwar/CaptchaBundle#234]
Hi , i'm trying to use your Captcha bundle but when i use to install it with composer there is an error : 
`#message: "Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /app/vendor/gregwar/captcha-bundle/Gregwar/CaptchaBundle/DependencyInjection/Configuration.php on line 16 and at least 1 expected"`

I'm pretty new in Symfony world and I don't know how to resolve it .
